global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'salon-core'
    static_configs:
      - targets: ['salon-core-1:8080', 'salon-core-2:8080']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-master:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-master:9121']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
