{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-cluster.fullname" . }}-secret
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.auth.password | quote }}
{{- end }}
