{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "salon-core.fullname" . }}
  labels:
    {{- include "salon-core.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "salon-core.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleDown.stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ .Values.autoscaling.scaleDown.percent }}
        periodSeconds: {{ .Values.autoscaling.scaleDown.periodSeconds }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleUp.stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ .Values.autoscaling.scaleUp.percentPolicy }}
        periodSeconds: {{ .Values.autoscaling.scaleUp.periodSeconds }}
      - type: Pods
        value: {{ .Values.autoscaling.scaleUp.podsPolicy }}
        periodSeconds: {{ .Values.autoscaling.scaleUp.periodSeconds }}
      selectPolicy: Max
{{- end }}
