apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.auth.postgresPassword | quote }}
  password: {{ .Values.auth.password | quote }}
  username: {{ .Values.auth.username | quote }}
  database: {{ .Values.auth.database | quote }}
